# Generated by Django 5.2.7 on 2025-10-04 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beats_per_measure', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('beat_unit', models.PositiveIntegerField(choices=[(2, '1/2'), (4, '1/4'), (8, '1/8'), (16, '1/16')])),
                ('volume', models.PositiveIntegerField(default=70, help_text='Громкость в процентах (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bpm', models.PositiveIntegerField(default=120, help_text='Ударов в минуту (30-300 BPM)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
            ],
        ),
    ]
