# Generated by Django 5.2.7 on 2025-10-16 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название пресета', max_length=100)),
                ('bpm', models.PositiveIntegerField(help_text='Темп в BPM', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('description', models.CharField(blank=True, help_text='Описание', max_length=200)),
                ('category', models.CharField(choices=[('classical', 'Классика'), ('popular', 'Популярная музыка'), ('rock', 'Рок'), ('jazz', 'Джаз'), ('electronic', 'Электронная'), ('custom', 'Пользовательская')], default='custom', max_length=20)),
            ],
            options={
                'ordering': ['bpm'],
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='beat_unit',
            field=models.PositiveIntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (16, '16')]),
        ),
    ]
