# Generated by Django 5.2.7 on 2025-10-17 17:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0002_tempopreset_alter_usersettings_beat_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_position', models.PositiveIntegerField(help_text='Позиция доли (0 - сильная доля)')),
                ('sound_type', models.CharField(choices=[('click', 'Клик'), ('beep', 'Бип'), ('woodblock', 'Вудблок'), ('drum', 'Барабан'), ('bell', 'Колокольчик'), ('triangle', 'Треугольник'), ('cowbell', 'Ковбелл'), ('tambourine', 'Бубен')], default='click', max_length=20)),
                ('volume', models.PositiveIntegerField(default=100, help_text='Громкость этой доли (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_sounds', to='metronome.usersettings')),
            ],
            options={
                'ordering': ['beat_position'],
                'unique_together': {('user_settings', 'beat_position')},
            },
        ),
    ]
